#!/usr/bin/env php
<?php
$argv = $_SERVER["argv"];
$dummy = array_shift($argv);

if ($argv[0] == '-l' || $argv[0] == '-list') {
	$files = glob(dirname(__FILE__).'/commands/*.php');
	foreach ($files as $file) {
		echo basename($file,'.php').chr(10);
	}
	die(chr(10));
}

$argv[0] = dirname(__FILE__).'/commands/'.$argv[0].'.php';

if (!file_exists($argv[0]))
	die('Command "'.$_SERVER["argv"][1].'" Not Found'.chr(10));

passthru(implode(' ', $argv));